[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=60",
    "setuptools-scm>=8.0"
    ]

[project]
name = "fms_mo"
version="0.1.0"
description = "Quantization Techniques"
authors = [
  {name = "Andrea Fasoli"},
  {name = "Brandon Groth"},
  {name = "Charlie Liu"},
  {name = "Derrick Liu"},
  {name = "Naigang Wang"},
  {name = "Thara Palanivel"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = "~=3.9"
keywords = ['quantization', 'python', 'pytorch']
classifiers=[
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
"torch >=2.1, <2.5",
"numpy",
"tqdm",
"tensorboard",
"notebook",
"torchvision>=0.8",
"transformers",
"accelerate",
"evaluate",
"datasets",
"huggingface_hub",
"pandas",
"safetensors",
"ninja",
]

[project.optional-dependencies]
fp8 = ["llmcompressor"]
gptq = ["auto_gptq"]
visualize = ["matplotlib", "graphviz", "pygraphviz"]

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]
namespaces = false

[project.urls]
Homepage = "https://github.com/foundation-model-stack/fms-model-optimizer"
Repository = "https://github.com/foundation-model-stack/fms-model-optimizer"
Issues = "https://github.com/foundation-model-stack/fms-model-optimizer/issues"
